// affichage de l'ensemble des Materiels
GET http://localhost:8081/api/materials

###

// affichage de l'ensemble des fournisseurs
GET http://localhost:8081/api/materials/fournisseurs

###


//ajout d'un Materiel
POST http://localhost:8081/api/materials
Content-Type: application/json

{
        "CodeBarre":5,
        "Nom":"myName",
        "Description":"myDescription",
        "Type":"myType"
}

###

// recherche d'un Materiel en fonction de son code barre
GET http://localhost:8081/api/materials/3

###
// modification d'un Materiel
PUT http://localhost:8081/api/materials/2346
Content-Type: application/json

{
        "Nom":"mynewName",
        "Description":"mynewDescription",
        "Type":"mynType"
}
###
// suppression d'un Materiel
DELETE http://localhost:8081/api/materials/2346